### ISSUE TITLE
Exception in v2.0.2-beta3 when starting Visual Studio 2013

### ISSUE THREAD

**Issue by thoemmi** [mike-ward/VSColorOutput#10]
I installed Beta 3 and starting Visual Studio 2013. When I opened a solution I got a message that some error was logged in ActivityLog.xml. 
![image](https://cloud.githubusercontent.com/assets/73690/11953189/8f6c02e2-a89e-11e5-9ac9-a37c34810b37.png)
There are two entries which I think are caused by VSColourOutput:

```
System.ComponentModel.Composition.CompositionException: The composition produced a single composition error. The root cause is provided below. Review the CompositionException.Errors property for more detailed information. 
1) The export 'Microsoft.VisualStudio.Text.Classification.Implementation.ClassificationTypeRegistryService (ContractName="Microsoft.VisualStudio.Text.Classification.IClassificationTypeRegistryService")' is not assignable to type 'Microsoft.VisualStudio.Text.Classification.IClassificationTypeRegistryService'. 
Resulting in: Cannot set import 'BlueOnionSoftware.OutputClassifierProvider.ClassificationRegistry (ContractName="Microsoft.VisualStudio.Text.Classification.IClassificationTypeRegistryService")' on part 'BlueOnionSoftware.OutputClassifierProvider'. Element: BlueOnionSoftware.OutputClassifierProvider.ClassificationRegistry (ContractName="Microsoft.VisualStudio.Text.Classification.IClassificationTypeRegistryService") --> BlueOnionSoftware.OutputClassifierProvider 
Resulting in: Cannot get export 'BlueOnionSoftware.OutputClassifierProvider (ContractName="Microsoft.VisualStudio.Text.Classification.IClassifierProvider")' from part 'BlueOnionSoftware.OutputClassifierProvider'. Element: BlueOnionSoftware.OutputClassifierProvider (ContractName="Microsoft.VisualStudio.Text.Classification.IClassifierProvider") --> BlueOnionSoftware.OutputClassifierProvider
at System.ComponentModel.Composition.Hosting.CompositionServices.GetExportedValueFromComposedPart(ImportEngine engine, ComposablePart part, ExportDefinition definition)
at System.ComponentModel.Composition.Hosting.CatalogExportProvider.GetExportedValue(CatalogPart part, ExportDefinition export, Boolean isSharedPart)
at System.ComponentModel.Composition.Hosting.CatalogExportProvider.CatalogExport.GetExportedValueCore() 
at System.ComponentModel.Composition.Primitives.Export.get_Value()
at System.ComponentModel.Composition.ExportServices.GetCastedExportedValue[T](Export export) at System.ComponentModel.Composition.ExportServices.<>c__DisplayClass11_0`2.<CreateStronglyTypedLazyOfTM>b__1() 
at System.Lazy`1.CreateValue() at System.Lazy`1.LazyInitValue() at System.Lazy`1.get_Value() 
at Microsoft.VisualStudio.Text.Utilities.GuardedOperations.InvokeMatchingFactories[TExtensionInstance,TExtensionFactory,TMetadataView](IEnumerable`1 lazyFactories, Func`2 getter, IContentType dataContentType, Object errorSource)
```
and
```
The color 'Popup' in category 'de7b1121-99a4-4708-aedf-15f40c9b332f' does not exist.
```

**Comment by mike-ward** [comment]
Thanks! I'll have a look.

**Comment by mike-ward** [comment]
Well this is a total bummer. By using VS 2015 for development I nixed backwards compatiblity with the earlier versions.

I'll leave the old version as is and launch a new version under a different name.

**Comment by mike-ward** [comment]
Total unbummer. Found out the issue was that the I need to build aganist the older SDK libs.

**Comment by thoemmi** [comment]
:laughing: :+1:

**Comment by mike-ward** [comment]
Beta 4 out. Give 'er as spin

https://github.com/mike-ward/VSColorOutput/releases

**Comment by thoemmi** [comment]
Beta 4 works in Visual Studio 2013 just fine. :+1:

**Comment by mike-ward** [comment]
cool!
