### ISSUE TITLE
Exception in VS2015 after "Find All..."

### ISSUE THREAD

**Issue by tom-englert** [mike-ward/VSColorOutput#24]
Got an exception in VS, with the following entry in the activity log:

```
System.ArgumentOutOfRangeException: Length cannot be less than zero.
Parameter name: length
   at System.String.Substring(Int32 startIndex, Int32 length)
   at VSColorOutput.FindResults.FindResultsClassifier.CanSearch(SnapshotSpan span)
   at VSColorOutput.FindResults.FindResultsClassifier.GetClassificationSpans(SnapshotSpan span)
   at Microsoft.VisualStudio.Text.Classification.Implementation.ClassifierTagger.&lt;GetTags&gt;d__5.MoveNext()
   at Microsoft.VisualStudio.Text.Tagging.Implementation.TagAggregator`1.&lt;GetTagsForBuffer&gt;d__38.MoveNext()
```

**Comment by mike-ward** [comment]
Thanks for the bug report.
