### ISSUE TITLE
Since update to latest VS2017, this plugin no longer works.

### ISSUE THREAD

**Issue by evilrix** [mike-ward/VSColorOutput#87]
The plugin stopped working after I performed a VS2017 update to the latest version. I removed and attempted to reinstall the plugin and it fails to install. Below is the installation log, which I hope helps resolve this issue.

Thanks.

```
17/04/2019 11:02:24 - Microsoft VSIX Installer
17/04/2019 11:02:24 - -------------------------------------------
17/04/2019 11:02:24 - vsixinstaller.exe version:
17/04/2019 11:02:24 - 15.9.3041
17/04/2019 11:02:24 - -------------------------------------------
17/04/2019 11:02:24 - Command line parameters:
17/04/2019 11:02:24 - C:\Program Files (x86)\Microsoft Visual Studio\Installer\resources\app\ServiceHub\Services\Microsoft.VisualStudio.Setup.Service\VSIXInstaller.exe,C:\Users\evilrix\Downloads\VSColorOutput.vsix
17/04/2019 11:02:24 - -------------------------------------------
17/04/2019 11:02:24 - Microsoft VSIX Installer
17/04/2019 11:02:24 - -------------------------------------------
17/04/2019 11:02:25 - Initializing Install...
17/04/2019 11:02:25 - Extension Details...
17/04/2019 11:02:25 - 	Identifier         : CD56B219-38CB-482A-9B2D-7582DF4AAF1E
17/04/2019 11:02:25 - 	Name               : VSColorOutput
17/04/2019 11:02:25 - 	Author             : Mike Ward
17/04/2019 11:02:25 - 	Version            : 2.6.5
17/04/2019 11:02:25 - 	Description        : Color output for build and debug windows
17/04/2019 11:02:25 - 	Locale             : en-US
17/04/2019 11:02:25 - 	MoreInfoURL        : http://mike-ward.net/vscoloroutput
17/04/2019 11:02:25 - 	InstalledByMSI     : False
17/04/2019 11:02:25 - 	SupportedFrameworkVersionRange : [4.5,)
17/04/2019 11:02:25 - 
17/04/2019 11:02:25 - 	SignatureState     : Unsigned
17/04/2019 11:02:25 - 	Supported Products : 
17/04/2019 11:02:25 - 		Microsoft.VisualStudio.Community
17/04/2019 11:02:25 - 			Version : [16.0,17.0)
17/04/2019 11:02:25 - 
17/04/2019 11:02:25 - 	References         : 
17/04/2019 11:02:25 - 	Prerequisites      : 
17/04/2019 11:02:25 - 		-------------------------------------------------------
17/04/2019 11:02:25 - 		Identifier   : Microsoft.VisualStudio.Component.CoreEditor
17/04/2019 11:02:25 - 		Name         : Visual Studio core editor
17/04/2019 11:02:25 - 		Version      : [15.0,)
17/04/2019 11:02:25 - 
17/04/2019 11:02:25 - Signature Details...
17/04/2019 11:02:25 - 	Extension is not signed.
17/04/2019 11:02:25 - 
17/04/2019 11:02:25 - Searching for applicable products...
17/04/2019 11:02:25 - Found installed product - Global Location
17/04/2019 11:02:25 - Found installed product - Visual Studio Community 2017
17/04/2019 11:02:25 - VSIXInstaller.NoApplicableSKUsException: This extension is not installable on any currently installed products.
   at VSIXInstaller.ExtensionService.GetInstallableData(String vsixPath, String extensionPackParentName, Boolean isRepairSupported, IStateData stateData, IEnumerable`1& skuData)
   at VSIXInstaller.ExtensionPackService.IsExtensionPack(IStateData stateData, Boolean isRepairSupported)
   at VSIXInstaller.ExtensionPackService.ExpandExtensionPackToInstall(IStateData stateData, Boolean isRepairSupported)
   at VSIXInstaller.App.Initialize(Boolean isRepairSupported)
   at VSIXInstaller.App.Initialize()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
```

**Comment by mike-ward** [comment]
You can get the previous version [here](https://github.com/mike-ward/VSColorOutput/releases/tag/v2.6.4). The updated version only works on 2019. No new features. Just some internal changes to accommodate the upcoming 2019 16.1 release.
